# Generated by Django 2.1.5 on 2021-05-29 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('katalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='instancjaksiazki',
            name='status',
            field=models.CharField(blank=True, choices=[('n', 'Naprawa'), ('w', 'Wypozyczona'), ('d', 'Dostepna'), ('z', 'Zarezerwowana')], default='n', help_text='Dostepnosc ksiazki', max_length=1),
        ),
    ]
